version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/blog/
    overwrite: yes
permissions:
  - object: /home/ec2-user/blog/
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 500
      runas: root
