# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Check Node v
        run: node -v
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: zip create
        run: zip -qq -r ./blog.zip ./.next/ ./appspec.yml ./deploy.sh
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./blog.zip s3://github-blog-deploy/blog.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name blog
          --deployment-config-name CodeDeployDefault.AllAtOnce          --file-exists-behavior OVERWRITE
          --deployment-group-name blog
          --s3-location bucket=github-blog-deploy,key=blog.zip,bundleType=zip
